# Generated by Django 5.1.4 on 2024-12-18 11:11

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_products_is_suggestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=2500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='identification code'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='', max_length=11, validators=[django.core.validators.RegexValidator(message='شماره شما باید با فرمت 09 وارد شود', regex='^09\\d{9}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
