# Generated by Django 5.1.4 on 2024-12-18 13:34

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_orders_identification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره شما باید با فرمت 09 وارد شود', regex='^09\\d{9}$')])),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=2500)),
                ('postal_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
