# Generated by Django 5.1.4 on 2024-12-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_orders_total_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
