# Generated by Django 5.1.4 on 2024-12-20 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_vendorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.vendors'),
        ),
    ]
