# Generated by Django 5.1.4 on 2024-12-20 14:35

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_vendorprofile_user_vendorprofile_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره شما باید با فرمت 09 وارد شود', regex='^09\\d{9}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to=core.models.VendorProfile.get_upload_path, validators=[core.models.validate_image]),
        ),
    ]
