# Generated by Django 5.1.4 on 2024-12-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_vendorprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True),
        ),
    ]
