# Generated by Django 5.1.4 on 2024-12-21 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_vendors_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره خودرا با فرمت صحیح 09 وارد کنید', regex='^09\\{9}$')]),
            preserve_default=False,
        ),
    ]
