# Generated by Django 5.1.4 on 2024-12-21 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره خودرا با فرمت صحیح 09 وارد کنید', regex='^09\\d{9}$')]),
        ),
    ]
